dnl Copyright (C) 2000 Alexandre Duret-Lutz <duret_g@epita.fr> 
dnl 
dnl This file is part of Heroes.
dnl 
dnl Heroes is free software; you can redistribute it and/or modify it under
dnl the terms of the GNU General Public License as published by the Free
dnl Software Foundation; either version 2 of the License, or (at your
dnl option) any later version.
dnl 
dnl Heroes is distributed in the hope that it will be useful, but WITHOUT
dnl ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
dnl FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
dnl for more details.
dnl 
dnl You should have received a copy of the GNU General Public License along
dnl with this program; if not, write to the Free Software Foundation, Inc.,
dnl 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
dnl 

AC_PREREQ(2.49a)

AC_INIT([src/heroes.c])

AC_COPYRIGHT([Copyright (C) 2000, Alexandre Duret-Lutz])

AC_CANONICAL_HOST

AM_INIT_AUTOMAKE([heroes], [0.6])
AC_DEFINE_UNQUOTED([HOST],["$host"],[The canonical host])

# ==================
# Supported options.
# ==================

AC_ARG_ENABLE([html-doc],
[AC_HELP_STRING([--enable-html-doc=DIR],
               [build and install html documentation])])
AC_ARG_ENABLE([sound],
[AC_HELP_STRING([--disable-sound],[turn off sound support])])
AC_ARG_ENABLE([debug],
[AC_HELP_STRING([--enable-debug],[turn on debugging])])
AC_ARG_ENABLE([heroes-debug],
[AC_HELP_STRING([--heroes-debug],[disable tracing facility])])
AC_ARG_ENABLE([mem-debug],
[AC_HELP_STRING([--mem-debug],[turn on memory debugging])])
AC_ARG_ENABLE([user-config],
[AC_HELP_STRING([--user-config],[turn off per user configuration file])])
AC_ARG_ENABLE([user-scores],
[AC_HELP_STRING([--disable-user-scores],[turn off per user scores file])])
AC_ARG_ENABLE([user-saves],
[AC_HELP_STRING([--disable-user-saves],[turn off per user saves file])])
AC_ARG_ENABLE([joystick],
[AC_HELP_STRING([--disable-joystick],[turn off joystick support])])
AC_ARG_WITH([sdl],
[AC_HELP_STRING([--with-sdl=DIR],[root directory of SDL installation])
AC_HELP_STRING([--without-sdl],[disables SDL usage completely])])
AC_ARG_WITH([mikmod],
[AC_HELP_STRING([--with-mikmod=DIR],
               [root directory of libMikMod installation])
AC_HELP_STRING([--without-mikmod],[disables libMikMod usage completely])])

# debugging options

if test "x$enable_debug" = xyes; then
  # disabled by default
  AC_DEFINE([DEBUG],1,[Define if you want debuging code and symbols.])
fi;

if test "x$enable_heroes_debug" != xno; then
  # enabled by default
  AC_DEFINE([USE_HEROES_DEBUG],1,[Define if you want tracing code.])
fi;

# --with-sdl-exec-prefix should imply --with-sdl, and vice-versa

test "${with_sdl_exec_prefix-no}" != no &&
 test "${with_sdl-yes}" = yes && with_sdl="$with_sdl_exec_prefix"

test "${with_sdl-yes}" != yes &&
 test "${with_sdl_exec_prefix-yes}" = yes && with_sdl_exec_prefix="$with_sdl"

# --with-mikmod-exec-prefix should imply --with-mikmod, and vice-versa

test "${with_mikmod_exec_prefix-no}" != no &&
 test "${with_mikmod-yes}" = yes && with_mikmod="$with_mikmod_exec_prefix"

test "${with_mikmod-yes}" != yes &&
 test "${with_mikmod_exec_prefix-yes}" = yes && 
   with_mikmod_exec_prefix="$with_mikmod"

# handle choice between GGI and SDL

if test "${with_GGI-no}" != no; then
  if test "${with_sdl-no}" != no; then
    AC_MSG_ERROR([GGI and SDL can't be both used.])
  fi
  # disable SDL if GGI was selected
  with_sdl=no
else
  if test "${with_sdl-no}" != no; then
    # disable	 GGI if SDL was selected
    with_GGI=no
  fi
fi

# handle choice between SDL_mixer and libMikmod

if test "${with_mikmod-no}" != no; then
  if test "${with_sdl_mixer-no}" != no; then
     AC_MSG_ERROR([libMikMod and SDL_mixer can't be both used.])
  fi
  # disable SDL_mixer if libMikMod was selected
  with_sdl_mixer=no
else
  if test "${with_sdl_mixer-no}" != no; then
    # disable libMikMod if SDL_mixer was selected
    with_mikmod=no
  fi
fi

# SDL_mixer imply SDL

if test "${with_sdl_mixer-no}" != no; then
  if test "${with_GGI-no}" != no; then
    AC_MSG_ERROR([GGI and SDL_mixer can't be both used.])
  fi
  with_GGI=no
fi

# Detect wether CFLAGS and LDFLAGS will be setup by autoconf or not.
test -z "${CFLAGS+set}"  && CFLAGS=  auto_cflags=1
test -z "${LDFLAGS+set}" && LDFLAGS= auto_ldflags=1

# These value will be updated according to detections.
display_lib='<disabled>'
joystick_lib='<disabled>'
sound_lib='<disabled>'
malloc_lib='<disabled>'

# ===================
# Check for programs.
# ===================

AC_PROG_CC
AC_PROG_CC_STDC
AC_PROG_CPP
AC_PROG_AWK
AC_PROG_RANLIB

usable_perl=false
AC_PATH_PROG([PERL], [perl])
if test \! -z "$PERL"; then
  AC_MSG_CHECKING([perl version])
  if $PERL -e 'printf "%g\n", $]; exit($] >= 5.004);'; then
    AC_MSG_WARN([perl 5.004 needed])
  else
    usable_perl=true 
  fi
fi
AM_CONDITIONAL(USABLE_PERL, [test "x$usable_perl" = xtrue])

AM_MISSING_PROG([HELP2MAN], [help2man], [\${SHELL} \${top_srcdir}])

AC_PATH_PROG([GPERF], [gperf])
AM_CONDITIONAL(HAVE_GPERF, [test \! -z "$GPERF"])

AC_CACHE_SAVE

# =====================
# Checks for libraries.
# =====================

# ==============
# Check for GGI.
# ==============

if test "${with_GGI-yes}" != no; then

AC_caolan_CHECK_PACKAGE(GGI,[ggiOpen],[ggi],[ggi/ggi.h],,[with_GGI=no])

fi
if test "${with_GGI-yes}" != no; then

# Where is <ggi/keyboard.h> located?
# (Adapted from Zsh's configure.in)
AC_CACHE_CHECK([where ggi/keyboard.h is located], [path_ggi_keyboard_h],
[# Look at the output from the preprocessor.
# We should get lines of the form `# 1 "/usr/include/ggi/keyboard.h"'
# The backslash substitution is to persuade cygwin to cough up
# slashes rather than doubled backslashes in the path.
echo "#include <ggi/keyboard.h>" > nametmp.c
keyfile_list="`$CPP nametmp.c |
sed -n 's/^#[ 	].*\"\(.*\)\"/\1/p' |
sed 's/\\\\\\\\/\//g' |
$AWK '{ if (\$1 ~ \"ggi/keyboard.h\") files[[\$1]] = \$1 }
  END { for (var in files) print var }'`"
rm -f nametmp.c
if test -z "$keyfile_list"; then
  # In case we don't get the stuff from the preprocesor, use the old
  # list of standard places.
  keyfile_list="/usr/include/ggi/keyboard.h
${GGI_include-/usr/local/include}/ggi/keyboard.h
/dev/null"
fi
for KEY_H in $keyfile_list
do
  # Try to make sure it doesn't get confused by files that don't
  # have real keysyms definitions in
  nkeys=`test -f $KEY_H && \
  grep '#[ 	]*define[ 	][ 	]*GIIUC*' $KEY_H | \
  wc -l | sed 's/[ 	]//g'`
  test "x$nkeys" != x && test "$nkeys" -ge 7 && break
done
if test $KEY_H = "/dev/null"; then
  AC_MSG_ERROR([Keysyms macros not found: where is GGI installed?])
fi
path_ggi_keyboard_h="$KEY_H"
])
GGI_KEYBOARD_H="$path_ggi_keyboard_h"
AC_SUBST([GGI_KEYBOARD_H])

with_sdl=no
display_lib=LibGGI
fi

# ==================
# Check for lib SDL.
# ==================

if test "${with_sdl-yes}" != no; then

AC_adl_PKG_GENERIC(sdl,[1.0.1],[SDL_Init],
[AC_DEFINE([HAVE_SDL],1,[Define if you have the SDL library.])],
[with_sdl=no])

fi
if test "${with_sdl-yes}" != no; then

# Where is <SDL_keysym.h> located?
# (Adapted from Zsh's configure.in)
AC_CACHE_CHECK([where SDL_keysym.h is located], [path_sdl_keysym_h],
[# Look at the output from the preprocessor.
# We should get lines of the form `# 1 "/usr/include/SDL/SDL_keysym.h"'
# The backslash substitution is to persuade cygwin to cough up
# slashes rather than doubled backslashes in the path.
echo "#include <SDL_keysym.h>" > nametmp.c
keyfile_list="`$CPP $SDL_CFLAGS nametmp.c |
sed -n 's/^#[ 	].*\"\(.*\)\"/\1/p' |
sed 's/\\\\\\\\/\//g' |
$AWK '{ if (\$1 ~ \"SDL_keysym.h\") files[[\$1]] = \$1 }
  END { for (var in files) print var }'`"
rm -f nametmp.c
if test -z "$keyfile_list"; then
  # In case we don't get the stuff from the preprocesor, use the old
  # list of standard places.
  keyfile_list="/usr/include/SDL/SDL_keysym.h
/usr/local/include/SDL/SDL_keysym.h
/dev/null"
fi
for KEY_H in $keyfile_list
do
  # Try to make sure it doesn't get confused by files that don't
  # have real keysyms definitions in
  nkeys=`test -f $KEY_H && \
  grep '#[ 	]*define[ 	][ 	]*SDLK_*' $KEY_H | \
  wc -l | sed 's/[ 	]//g'`
  test "x$nkeys" != x && test "$nkeys" -ge 7 && break
done
if test $KEY_H = "/dev/null"; then
  AC_MSG_ERROR([Keysyms definitions not found: where is SDL installed?])
fi
path_sdl_keysym_h="$KEY_H"
])
SDL_KEYSYM_H="$path_sdl_keysym_h"
AC_SUBST([SDL_KEYSYM_H])
display_lib="SDL dnl
$sdl_config_major_version.$sdl_config_minor_version.$sdl_config_micro_version"
AC_CHECK_FUNCS([SDL_EnableKeyRepeat])
fi

# ================================================
# Check that either LibGGI or SDL have been found.
# ================================================

if test x${with_sdl} = xno && test x${with_GGI} = xno; then
  AC_MSG_ERROR([Heroes can't compile without a graphic library.

Heroes requires either GGI or SDL to be installed on your system.
See the README file for pointers towards those libraries.
])
fi
AM_CONDITIONAL(GGI, [test "x${with_GGI}" != xno])
AM_CONDITIONAL(SDL, [test "x${with_sdl}" != xno])

# =================
# Joystick support.
# =================

if test "${enable_joystick-yes}" = yes; then

  # -- check for Joystick support in SDL
  
  sdl_joystick=no
  if test "${with_sdl-yes}" != no && test "${with_GII-no}" = no;  then
    AC_CHECK_FUNCS([SDL_JoystickOpen],[
sdl_joystick=yes
joystick_lib="SDL dnl
$sdl_config_major_version.$sdl_config_minor_version.$sdl_config_micro_version"
])
  fi

  # -- check for LibGGI (another way to get joystick support)

  gii_joystick=no
  if test $sdl_joystick = no && test "${with_GII-yes}" != no;  then
    AC_caolan_CHECK_PACKAGE([GII],[giiOpen],[gii],[ggi/gii.h],[
gii_joystick=yes
joystick_lib='LibGII'
])
  fi

  if test $sdl_joystick = no && test $gii_joystick = no; then
    enable_joystick=no
  fi
fi

if test "${enable_joystick-yes}" = yes; then
  AC_DEFINE([JOYSTICK_SUPPORT],1,[Define if you want joystick support.])
fi

# ===================
# Check for lib math.
# ===================

AC_CHECK_LIB([m],[sin])

# ==========================
# Check for sound libraries.
# ==========================

if test "${enable_sound-yes}" != no; then

# ====================
# Check for SDL_mixer.
# ====================

if test "${with_sdl-yes}" != no && test "${with_sdl_mixer-yes}" != no; then

# temporaly put the CFLAGS for SDL in CPPFLAGS
# so that AC_caolan_CHECK_PACKAGE can find SDL_mixer.h in the same directory.
tmp_CPPFLAGS="$CPPFLAGS"
CPPFLAGS="$SDL_CFLAGS $CPPFLAGS"

AC_caolan_CHECK_PACKAGE([sdl_mixer],[Mix_OpenAudio],[SDL_mixer],[SDL_mixer.h],,
[with_sdl_mixer=no])
if test "x${with_sdl_mixer}" != xno; then
  sound_lib="SDL_mixer"
  with_sdl_mixer=yes
fi

# revert old value
CPPFLAGS="$tmp_CPPFLAGS"

fi # with_sdl_mixer

# ====================
# Check for LibMikMod.
# ====================

if test "${with_sdl_mixer-no}" = no; then

AC_adl_PKG_GENERIC([libmikmod],[3.1.7],[MikMod_Init],
[sound_lib="libmikmod dnl
$libmikmod_config_major_version.$libmikmod_config_minor_version.dnl
$libmikmod_config_micro_version"
]AC_DEFINE([HAVE_LIBMIKMOD],1,[Define if you have the LibMikMod library.]))

fi

fi # enable_sound

# ==================
# Check for dmalloc.
# ==================

mallocdbg='';

if test "x${enable_mem_debug}" = xyes; then
  AC_CHECK_LIB([dmalloc],[malloc],[mallocdbg='dmalloc'; 
malloc_lib='dmalloc'; LIBS="-ldmalloc $LIBS";
AC_DEFINE([HAVE_DMALLOC],1,[Define if you link with the dmalloc library.])])
fi

# =========================
# Check for electric fence.
# =========================

if test "x${enable_mem_debug}" = xyes; then
  if test "x${mallocdbg}" = x; then
    AC_CHECK_LIB([efence],[malloc],[mallocdbg='efence'; 
malloc_lib='electric fence'; LIBS="-lefence $LIBS"])
  fi
fi

# ========================
# Checks for header files.
# ========================

AC_HEADER_STDC
AC_HEADER_DIRENT
AC_CHECK_HEADERS(
 [memory.h] dnl
 [stdint.h] dnl
 [string.h] dnl
 [strings.h] dnl
 [sys/time.h] dnl
 [unistd.h] dnl
 [windows.h] dnl
)
AC_HEADER_TIME
AC_HEADER_STAT

# ==============================================================
# Checks for typedefs, structures, and compiler characteristics.
# ==============================================================

AM_C_PROTOTYPES
AC_C_CONST

# =============================
# Checks for library functions.
# =============================

AC_CHECK_FUNCS([gettimeofday memcpy sleep])

# Heroes needs opendir, readdir and closedir.  We check only for
# readdir and assume that opendir and closedir are present if readdir is.
# Under plain Win32 (i.e. not Mingw or Cygwin) these functions are not
# available, but can be faked with lib/w_dirent.c.  It's a bit odd to
# perform that test here, since "plain Win32" users will never run 
# configure... Hence this code only documents when w_dirent.c should
# be built.
AC_CHECK_FUNC([readdir],
              [AC_DEFINE([HAVE_READDIR],1,
                         [Define if you have readdir and friends.]
                        )],
              [if test "x$ac_cv_header_windows_h" = xyes; then
                 dnl don't quote w_dirent or automake won't understand.
                 AC_LIBOBJ(w_dirent)
	       else
                 AC_MSG_ERROR([Could not find `readdir'.])
	       fi;])
AC_FUNC_VPRINTF

AC_CACHE_CHECK([whether mkdir takes two arguments],[ac_cv_two_args_mkdir],
[AC_TRY_COMPILE([#include <unistd.h>],[mkdir (".", 0777);],
[ac_cv_two_args_mkdir=yes],[ac_cv_two_args_mkdir=no])])
if test $ac_cv_two_args_mkdir = yes; then
  AC_DEFINE([TWO_ARGS_MKDIR],1,[Define if mkdir take two arguments.])
fi

AC_REPLACE_FUNCS([strcasecmp])

AC_SUBST([LIBOBJS])

# ====================
# Check for endianess.
# ====================

case "$build" in
  $host)
    # if the build host is the host, we can test endianess 
    # by running a small test program
    AC_C_BIGENDIAN
    ;;
  *)
    # otherwise (if a cross build is being done) we rely on an explicit
    # table of known hosts.
    AC_MSG_CHECKING([for byte ordering])
    case "$host" in
      i?86-*|alpha-*|arm-*)
	AC_MSG_RESULT([assuming little endian])
        ;;
      sparc-*|m68k-*)
	AC_MSG_RESULT([assuming big endian])
	AC_DEFINE([WORDS_BIGENDIAN])
        ;;
      *)
        AC_MSG_ERROR([
Cross-compiling requires knowing the byte ordering of $host.
Please report this information to <heroes-bugs@lists.sourceforge.net>
so that this knowledge can be added to ./configure in next release.])
        ;;
    esac
  ;;
esac

# =============================================================
# Setup the correct compiler options whether the
# user enabled debug or not.  (Adapted from Zsh's configure.in)
# =============================================================

if test "x${enable_debug}" != xyes && test -n "$GCC"; then
  CFLAGS="$CFLAGS -DNDEBUG"
fi

if test -n "$auto_cflags"; then
  if test "x${enable_debug}" = xyes; then
    if test -n "$GCC"; then
      CFLAGS="$CFLAGS -Wall -W -Wmissing-prototypes -ggdb"
    else
      CFLAGS="$CFLAGS -g"
    fi
  else
    if test -n "$GCC"; then
      CFLAGS="$CFLAGS -ffast-math -fstrict-aliasing -fomit-frame-pointer -O3"
    else
      CFLAGS="$CFLAGS -O"
    fi
  fi
fi
if test -n "$auto_ldflags"; then
  case "${enable_debug}$host_os" in
    yesaix*|yeshpux*|yesnetbsd*) ;;  # "ld -g" is not valid on these systems
    yes*)    LDFLAGS=-g ;;
    *)       LDFLAGS=-s ;;
  esac
fi

# =========================
# Directories configuration
# =========================

user_dir=no
if test "${enable_user_scores-yes}" != no; then
  AC_DEFINE([USER_SCORES_FILE],1,
            [Define if scores must be saved in the user directory.])
fi
if test "${enable_user_config-yes}" != no; then
  AC_DEFINE([USER_CONFIG_FILE],1,
            [Define if configuration must be saved in the user directory.])
fi
if test "${enable_user_saves-yes}" != no; then
  AC_DEFINE([USER_SAVES_FILE],1,
            [Define if games must be saved in the user directory.])
fi

confdir=${datadir}/heroes/txt_cfg/
extradir=${datadir}/heroes/extralvl/
scoresdir=${datadir}/heroes/txt_cfg/
textdir=${datadir}/heroes/txt_cfg/
etcdir=${datadir}/heroes/etc/
data_dir=${datadir}/heroes

AC_SUBST([confdir])
AC_SUBST([extradir])
AC_SUBST([scoresdir])
AC_SUBST([textdir])
AC_SUBST([etcdir])

AC_DEFINE_DIR([datadir],[data_dir],[Path to the data directory.])

# ===================
# HTML documentation. 
# ===================

# disabled by default
if test "${enable_html_doc-no}" != no; then
  if test "x$enable_html_doc" = xyes; then
    htmldir="$data_dir/doc"
  else
    htmldir="$enable_html_doc"
  fi
  AC_SUBST([htmldir])
else
  htmldir='\<none\>'
fi
AM_CONDITIONAL(MAKE_HTML, [test "${enable_html_doc-no}" != no])

# ============
# Output files
# ============

AM_CONFIG_HEADER(src/config.h) dnl DO NOT quote, this is parsed by automake.
AC_OUTPUT([
 Makefile
 lib/Makefile
 src/Makefile
 src/etc/Makefile
 src/txt_cfg/Makefile
 man/Makefile
 doc/Makefile
])

# ====================
# Configuration report
# ====================

eval bindir="$bindir"
eval bindir="$bindir"
eval datadir="$datadir"
eval mandir="$mandir"
eval infodir="$infodir"
eval htmldir="$htmldir"

echo "
Heroes configuration
--------------------
Heroes version           : $VERSION
host                     : $host
display & keyboard       : ${display_lib}
joystick                 : ${joystick_lib}
sound                    : ${sound_lib}"
test x$mallocdbg = x || echo "dnl
mem-debug                : ${malloc_lib}"
echo "dnl
compiler                 : $CC
compiler flags           : $CFLAGS
linker flags             : $LDFLAGS $LIBS
binary install path      : $bindir
data install path        : ${datadir}/heroes
manual page install path : $mandir
info manual install path : $infodir
html doc install path    : $htmldir"
