# Copyright 2000  Alexandre Duret-Lutz <duret_g@epita.fr>
#
# This file is part of Heroes.
#
# Heroes is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# Heroes is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

SUBDIRS = etc

bin_PROGRAMS = heroes

INCLUDES = -I$(top_srcdir)/lib -I../lib -I../intl -I.. -I.
LDADD = @INTLLIBS@ ../lib/libheroes.a

# DATADIRNAME is set to share (or lib) by AM_GNU_GETTEXT, this has nothing
# to do with datadir.  If heroes is configured with --prefix=/usr
# --bindir=/usr/games --datadir=/usr/share/games as the HFS requests,
# locale data will go into /usr/share/locale.  This comply with HFS.
localedir = $(prefix)/@DATADIRNAME@/locale
DEFS = -DLOCALEDIR=\"$(localedir)\" @DEFS@

EXTRA_DIST = rsc_files.gperf debughash.gperf

heroes_SOURCES = \
argv.c \
argv.h \
bonus.c \
bonus.h \
bytesex.h \
const.c \
const.h \
debughash.c \
debughash.h \
debugmsg.c \
debugmsg.h \
display.c \
display.h \
endscroll.c \
endscroll.h \
errors.c \
errors.h \
explosions.c \
explosions.h \
extras.c \
extras.h \
fader.c \
fader.h \
fastmem.h \
font.h \
font_help.h \
fontdata.c \
fontdata.h \
generic_list.h \
hedlite.c \
hedlite.h \
helptext.c \
helptext.h \
hendian.c \
hendian.h \
heroes.c \
heroes.h \
intro.c \
intro.h \
items.c \
items.h \
joystick.c \
joystick.h \
keyb.c \
keyb.h \
keys_heroes.h \
keysdef.c \
keysdef.h \
menus.c \
menus.h \
misc.c \
misc.h \
musicfiles.c \
musicfiles.h \
options.c \
options.h \
parafmt.c \
parafmt.h \
pcx.c \
pcx.h \
pixelize.c \
pixelize.h \
readmake.c \
readmake.h \
render.c \
render.h \
renderdata.c \
renderdata.h \
rsc_files.c \
rsc_files.h \
rsc_files_hash.c \
rsc_files_hash.h \
savegame.c \
savegame.h \
scores.c \
scores.h \
scrtools.c \
scrtools.h \
sfx.c \
sfx.h \
sound.c \
sound.h \
sprglauto.c \
sprglauto.h \
sprglenz.c \
sprglenz.h \
sprite.c \
sprite.h \
spropaque.c \
spropaque.h \
sprprog.c \
sprprog.h \
sprprogwav.c \
sprprogwav.h \
sprrle.c \
sprrle.h \
sprshade.c \
sprshade.h \
sprtext.c \
sprtext.h \
sprunish.c \
sprunish.h \
sprzcol.c \
sprzcol.h \
structs.h \
system.h \
timer.c \
timer.h \
userconf.c \
userconf.h \
userdir.c \
userdir.h \
visuals.c \
visuals.h

BUILT_SOURCES = keysdef-inc.h rsc_files_hash.c
DISTCLEANFILES = keysdef-inc.h

# This explicit dependency is needed, otherwise automake 1.4a
# dependecies won't bootstrap: dependencies are generated as a side
# effect of compilation, but keysdef.c can't be compiled if
# keysdef-inc.h has not been built.
keysdef.c: keysdef-inc.h

if GGI
keysdef-inc.h:
	@AWK@ ' \
BEGIN { print "/* Do not edit!\n" \
	      "   This file was generated by src/Makefile\n" \
	      "   from @GGI_KEYBOARD_H@ */\n" \
	      "#ifndef HEROES__KEYSDEF__INC__H__\n" \
	      "#define HEROES__KEYSDEF__INC__H__\n" \
	      "const struct keynames_s keynames[] = {" } \
$$2 ~ /(GIIK_|GIIUC_)/ { \
	print "\t{ \""toupper(substr($$2,index($$2,"_")+1))"\",", $$2,"}," } \
END { print "\t{ 0, 0 }};\n#endif\n" }' < @GGI_KEYBOARD_H@ > $@
else
if SDL
keysdef-inc.h:
	@AWK@ ' \
BEGIN { print "/* Do not edit!\n" \
	      "   This file was generated by src/Makefile\n" \
	      "   from @SDL_KEYSYM_H@ */\n" \
	      "#ifndef HEROES__KEYSDEF__INC__H__\n" \
	      "#define HEROES__KEYSDEF__INC__H__\n" \
	      "const struct keynames_s keynames[] = {" } \
$$1 ~ /SDLK_/ { \
	print "\t{ \""toupper(substr($$1,index($$1,"_")+1))"\",", $$1,"}," } \
END { print "\t{ 0, 0 }};\n#endif\n" }' < @SDL_KEYSYM_H@ > $@
else
keysdef-inc.h:
	echo "const struct keynames_s keynames[] = { { 0, 0 } };" > $@
endif
endif

if HAVE_GPERF
rsc_files_hash.c: rsc_files.gperf
	gperf -t -L ANSI-C -G -N in_rsc_set -W rsc_set \
	      -k 1,7,$$ $(srcdir)/rsc_files.gperf | \
	sed -e 's/{""}/{"",0,0,0}/g' > $@

debughash.c: debughash.gperf
	gperf -t -L ANSI-C -G -N in_channel_set -W channel_set \
	      -k 1,3,$$ $(srcdir)/debughash.gperf | \
	sed -e 's/{""}/{"",0,0}/g' > $@
endif

# This is handled manually, until Automake allows per-target CFLAGS
parafmt-check.o: parafmt.c
	@rm -f parafmt-check.o
	$(COMPILE) -DTEST $< -c -o $@

parafmt-check: parafmt-check.o
	@rm -f parafmt-check
	$(LINK) $< $(heroes_LDADD) -o $@
